// <auto-generated />
using System;
using CrazyDashCam.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrazyDashCam.Migrations
{
    [DbContext(typeof(TripDbContext))]
    partial class TripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CrazyDashCam.Database.DbAmbientAirTemperature", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("AmbientAirTemperatures");
                });

            modelBuilder.Entity("CrazyDashCam.Database.DbCoolantTemperature", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("CoolantTemperatures");
                });

            modelBuilder.Entity("CrazyDashCam.Database.DbEngineLoad", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("EngineLoads");
                });

            modelBuilder.Entity("CrazyDashCam.Database.DbFuelLevel", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("FuelLevels");
                });

            modelBuilder.Entity("CrazyDashCam.Database.DbIntakeTemperature", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("IntakeTemperatures");
                });

            modelBuilder.Entity("CrazyDashCam.Database.DbOilTemperature", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("OilTemperatures");
                });

            modelBuilder.Entity("CrazyDashCam.Database.DbRpm", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Timestamp");

                    b.ToTable("Rpms");
                });

            modelBuilder.Entity("CrazyDashCam.Database.DbSpeed", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Timestamp");

                    b.ToTable("Speeds");
                });

            modelBuilder.Entity("CrazyDashCam.Database.DbThrottlePosition", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("ThrottlePositions");
                });
#pragma warning restore 612, 618
        }
    }
}
