// <auto-generated />
using System;
using CrazyDashCam.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrazyDashCam.Shared.Migrations
{
    [DbContext(typeof(TripDbContext))]
    [Migration("20250111115419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbAmbientAirTemperature", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("AmbientAirTemperatures");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbCoolantTemperature", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("CoolantTemperatures");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbEngineLoad", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("EngineLoads");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbFuelLevel", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("FuelLevels");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbIntakeTemperature", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("IntakeTemperatures");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbLocation", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbOilTemperature", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("OilTemperatures");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbRpm", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Timestamp");

                    b.ToTable("Rpms");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbSpeed", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Timestamp");

                    b.ToTable("Speeds");
                });

            modelBuilder.Entity("CrazyDashCam.Shared.Database.DbThrottlePosition", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("ThrottlePositions");
                });
#pragma warning restore 612, 618
        }
    }
}
